### PR TITLE
Added select() to the API

### PR DESCRIPTION
**Pull request by connor**
Added in the source and the API documentation.

<3

### CODE REVIEW

**Comment by ded** [comment]
hmmm.... maybe this belongs in bean? i don't know

**Comment by connor** [comment]
i don't think so, since this isn't the select event. bean already has the select event in it - i wanted to be able to select all the text in an input this weekend in a project, and with Qwery/Bonzo, since it's not part of the API, I had to use raw js. This adds the ability to just call $('input').select(), and then it'll select all the text in there.

@fat whaddya think?

**Comment by fat** [comment]
nope, not an event thing, so i don't think it should go in bean

**Comment by ded** [comment]
um.... it is an event thing, actually

**Comment by ded** [comment]
oh........ uuuuuuuuuugh. okay, selecting text.... hhhhhhhmmmmmmmmmmmmmmmmm

**Comment by rvagg** [comment]
http://api.jquery.com/select/ (stupid)

-1 from me cause of this conflict and the likelyhood of confusion

**Comment by rvagg** [comment]
I'm going to close this because I've just remembered that we mirror that (stupid) jQuery select() method in the Bean bridge, listen to select events.

**Pull request closed without merging**
