### PR TITLE
Use classList if the browser support it

### PR DESCRIPTION
**Pull request by Calvein**
It's way faster : http://jsperf.com/classlist-vs-bonzo

I first pull request to the brand new `vanilla-masonry` repo by David DeSandro (https://github.com/desandro/vanilla-masonry/pull/3)

### CODE REVIEW

**Comment by ded** [comment]
pre-define the methods on load rather than each run-time operation, then we got a pull request.

eg:

``` js
var hasClass = features.classList ? function (el, c) {
  return el.classList.contains(c)
} : function (el, c) {
  return classReg(c).test(el.className)
}
```

**Comment by Calvein** [comment]
Done (I'll add this to masonry too).

**Comment by ded** [comment]
why do you suppose i got something like this from that test page? perf

**Comment by jots** [comment]
Hey guys, what do you think about this implementation:

http://jsperf.com/class-stuff

idea from: https://github.com/rightjs/rightjs-core/blob/master/src/dom/element/styles.js

**Comment by Calvein** [comment]
@ded ClassList is a bit slower than the RegExp on Chrome 15 but a bit faster on Chrome 16/17, in 2 weeks nobody will use Chrome 15 anymore. And it's way faster on Firefox/Opera.

@jots That's nice but it looks like classList will be faster on Firefox/Opera, we may let the classList, it's up to @ded.

**Pull request merged**
