### PR TITLE
Fixed issue #6

### PR DESCRIPTION
**Pull request by dawnerd**
Updated .show() to accept a display property. If no property is set, block is used.

### CODE REVIEW

**Comment by ded** [comment]
the merits of this are good. please use the submodule reference to the sink tests. do:

```
$ git submodule update --init
```

also, consider changing the code to:

```
style. display = type || "";
```

**Comment by dawnerd** [comment]
Is there any reason why elements is passed into both .show and .hide? It doesn't look like it's being used. I'm making the changes you suggested right now.

**Comment by ded** [comment]
reason is that it was accidentally left from old. it can be removed now.

**Comment by ded** [comment]
also, thanks for being patient as I check thru emails, twitters, and github.... my wife has been in labor the last few hours :/

**Comment by dawnerd** [comment]
Oh wow! I'll have an updated patch ready sometime tonight.

**Pull request merged**
