### PR TITLE
Normalize inputs to Bonzo constructor with version bump.

### PR DESCRIPTION
**Pull request by aawwawa**

### CODE REVIEW

**Comment by aawwawa** [comment]
Couldn't find any tests that were apparently in need of updating.

**Comment by rvagg** [comment]
This is what I was writing in the other issue as you posted this so I'll cut/paste it here:

---

I think you should have a crack at it @adlwalrus, you can submit an early pull-request and we can talk you through what needs to be done. Preferably you'd start with tests and implement after you have failing tests but feel free to do tests later if that's more comfortable to you.

The logic for this is currently implemented in the Ender bridge code for [Qwery](https://github.com/ded/qwery/blob/master/src/ender.js#L15-L33), that particular section takes care of the branching needed to do a DOM query vs a `bonzo.create()`, but you're guaranteed of having a string there.

Ignore the complicated nested functions and function reassignment and try/catch and `require` stuff, the important part is when to decide to do a `create()` vs a selector query. You need to insert that logic into `function Bonzo() {}` under a `typeof elements == 'string'` branch.

@ded's probably going to prefer this be implemented as nested ternarys too.

---

Looking at your code, there's a couple of things to note:
- You should probably do this in `Bonzo` not `bonzo`, there's already branching logic there
- You have to take into account the case of a selector string, see how this is done in `insert()` but also take note of the Qwery code I linked to above. You _may_ or _may not_ have a `query` function so you'd need to test for that like `insert()` does

On the actuall pull request:
- Don't bother bumping the version number, let the maintainer bother with that
- Edit _src/bonzo.js_ and commit that only, not the _bonzo.js_ in the root directory, that one's built using the _Makefile_

Try and think up some ways to test this too and write some new tests for it. I think some tests could cover, at a minimum:
1. `bonzo(element)`
2. `bonzo(elements)`
3. `bonzo(selectorString)`
4. `bonzo(htmlString)`
5. `bonzo()`

Then check that they all return the Bonzo object with the elements you expect.

And lastly, be patient, don't expect this to happen with particular speed from our end. Capiche?

**Comment by ded** [comment]
good coaching advice :+1:

**Comment by aawwawa** [comment]
As far as speed goes, np, capiche!

---

How does this look? It's slightly different than what you suggested, but I think it still accounts for the non-string cases you mentioned, by delegating the `bonzo.create()` call to `normalize()`...

``` js

  function Bonzo(elements) {
    this.length = 0
    if (elements) {
      elements = typeof elements === 'string' &&
        !elements.match(/^\s*</) &&
        query ?
          query(elements) :
          normalize(elements)
      this.length = elements.length
      for (var i = 0; i < elements.length; i++) this[i] = elements[i]
    }
  }
```

Sorry about the version numbers and wrong `bonzo.js`!

**Comment by rvagg** [comment]
I think that's looking pretty good I think; except note that `string.match(regex)` is a fair bit slower than `regex.test(string)`, partly because it only has to return a boolean vs an array of results.

Another note, if you make a new commit to your branch (or close the pull request and start a new branch to work without the commits you've already made then open a new pull request) we can comment line-by-line in the pull request rather than doing it just in these comments. Commits accumulate in a pull request until it's merged or closed so you can keep pushing to if you want to change stuff.

@ded I've just pushed a minor change, 567f89f, so that `query` defaults to `doc.querySelectorAll`, I was pondering what the default `!query` should be and decided that it really should just be qSA where it exists and caveat emptor otherwise. OK with that?

**Comment by aawwawa** [comment]
Ah, sorry, I'm generally not too concerned with client-side performance, and opt for what I see as superior code readability.  But I'll change it up..

As far as qSA goes, I was actually toying with that myself, believe it or not. But I didn't get very far... in my fiddlings-around, for some reason I got errors when testing `bonzo('selector')` after performing a `bonzo.setQueryEngine(document.querySelectorAll)`... But I quite like the idea itself.

Also, I manually console-tested all the cases you suggested, but I wouldn't know where or how to include them as automated tests...

**Comment by aawwawa** [comment]
Figured it out! It needed to be `bonzo.setQueryEngine(document.querySelectorAll.bind(document))`!

However, @rvagg -- doesn't this effectively hike bonzo's browser support line up to IE8+, as it's encouraging code that relies on the `bonzo(selectorstring)` syntax, but which doesn't have any kind of fallback should the loadtime `query` assignment fail?

**Comment by rvagg** [comment]
ya, don't use `bind()`, that's ES5-only. You need to grab the latest from ded/bonzo into your working branch cause I did it in 567f89f already. If you don't have ded/bonzo as a remote yet then `git remote add ded git@github.com:ded/bonzo.git` and then `git pull ded master` to pull in that new commit into your branch and you'll have a working `query()` without having to `setQueryEngine()` at all.

**Comment by aawwawa** [comment]
Good call on ES5... I realized that as I was falling asleep last night... Couldn't quite figure out why you were wrapping it in a function, but then I did.

What about my other concerns on IE-compatibility, though?

**Comment by rvagg** [comment]
Sorry yes, browsers without `qSA` aren't going to work without a plugged in selector engine and we'd just make note of that in the docs. I have exactly the same thing in Traversty and a note is fine: https://github.com/rvagg/traversty#selector-engines - Bonzo will need to say almost the same thing (except Bonzo won't use `matchesSelector` so it can go naked on one version of IE below Traversty).

There's plenty of demand these days to just support newer browsers, particularly for mobile dev where `qSA` is ubiquitous.

**Comment by aawwawa** [comment]
IMHO, there would then need to be at the least an asterisk next to the IE6 item under browser support, because you're providing a feature with no IE parity. I personally don't think your last point is valid, because Zepto is there to fill such demand, and makes no secret of it, at that. I think a choice should be made... either provide graceful degradations for the browsers you're claiming to support, or do what Zepto did, and opt for not giving yourself a headache at every turn of your considerably-lighter codebase. Sorry if I just came off grumpy -- I totally didn't mean to.

Anyhow, I'm not sure if it would be out of the scope of bonzo's codebase, but what about packaging something like [this](https://gist.github.com/cf04b98ce3128303d714) in with bonzo, and then supporting more advanced selectors with a bring-your-own-selector-engine scheme, if you want to provide some selection capabilities out of the box?

**Comment by rvagg** [comment]
No, people are advised to use Qwery, it's a natural pair for Bonzo. Alternatives that would do the same job are Sel, Sizzle and NWMatcher, Zest should also work too. It's up to the user to insert a selector engine if they care for it.
Additionally, the primary use of Bonzo is within an Ender build where a selection engine is wired up automatically and there again, building in a selection engine is left to the user.
And besides, there are many sites / devs who are stopping supporting IE6 and IE7 now, they are effectively EOL. IE8 is on the way out too, so this whole thing is relatively moot.

**Comment by ded** [comment]
moooooooooot

**Comment by aawwawa** [comment]
> It's up to the user to insert a selector engine if they care for it.

Agreed! So why are we inserting one for them?

Primary use? IDK, one of the things I found most admirable about bonzo was it's consideration for all the possible usecases.. :( As far as mootness is concerned, you're both pretty much right, I think, except for adjusting the browser support statement. No?

**Comment by rvagg** [comment]
no, no adjustment, just a note about that particular "feature" needing a new browser or a selector engine plugged in (ideally the latter in most cases to smooth over differences amongst the various browsers).

:cow: MOOOOO(t)

**Comment by aawwawa** [comment]
fair 'nough.

**Pull request closed without merging**
