### PR TITLE
add focus() and blur() to bonzo

### PR DESCRIPTION
**Pull request by connor**
- also documented in the API section of the README
- this closes the issue @fat [brought up in Ender's repo](https://github.com/ender-js/ender-js/issues/6).

### CODE REVIEW

**Comment by connor** [comment]
if you target more than one element, only the last one gets focused, since only one can be focused at a time.

**Comment by ded** [comment]
you'll want to only focus the first item in the selection. and also for build purposes, edit the file in the `src/` directory

**Comment by connor** [comment]
cool. will fix that tonight and edit my pull request.

**Comment by connor** [comment]
@ded I figured I should keep the code that iterates over all the selection and blurs it, just for more flexibility. If someone targets a class of inputs, and calls `blur()` on them, I figure it should blur them all no matter what, not just the first one. However, if they are doing that for `focus()`, I think it makes sense to focus only the first one. 

Anyways - the updated code's there. Let me know if you want me to change anything else!

**Comment by rvagg** [comment]
You'll probably want a test of some kind in `focus()` that makes sure you don't get an exception when `this.length==0`.

**Comment by connor** [comment]
right. thanks for catching that! just coded up the fix really quick and didn't even consider that. will adjust this and make a new Pull Request!

**Pull request merged**
